### ISSUE TITLE
In need of assistance

### ISSUE THREAD

**Issue by Catmasta101** [RoboMWM/AzureResizer#1]
This is really cool but i need some help in using it. I've managed to get it to compile and got it installed but whenever its time to restart console prints unknown command and nothing happens.
Thanks in advance

(also this as a fabric mod would be really neat and im considering learning how to make mods to port it over)

**Comment by Catmasta101** [comment]
I'm just going to go ahead and close this.

**Comment by RoboMWM** [comment]
I must've missed the notification, but without any info I can't help you lol.
